Start Swift Concurrency Implementation of UBURLDataTask
UbiqueInnovation/ubkit-ios pull request #23
Opened 2022-05-16 15:23 UTC by maerki

2023-01-26 07:18 UTC, ubamrein requested changes

2023-01-26 07:18 UTC, ubamrein commented on Sources/UBFoundation/Networking/Concurrency/UBURLDataTask+Concurrency.swift
> +        /// - Throws: if Result is a failure
Stimmt der kommentar?

2023-01-26 07:18 UTC, ubamrein commented on Sources/UBFoundation/Networking/Concurrency/UBURLDataTask+Concurrency.swift
> +    func startCronStream<T>(decoder: UBURLDataTaskDecoder<T>) -> AsyncThrowingStream<(T, MetaData), Error> {
Wieso cron? Wieso keine doc comments?

2023-01-26 07:18 UTC, ubamrein commented on Sources/UBFoundation/Networking/UBURLRequestModifier+TokenAuthorization.swift
> +public extension UBAsyncURLRequestTokenAuthorization {
```suggestion
public extension UBAsyncURLRequestBearerTokenAuthorization {
```

Wenn nur bearer token benutzt werden, würde ich den Funktionsnamen explizit machen.

2023-01-26 07:18 UTC, ubamrein commented on Sources/UBFoundation/Networking/UBURLRequestModifier.swift
> +                var newRequest = originalRequest
Macht das eine deep copy vom UBURLRequest mit dem ganzen payload?

2023-01-26 07:18 UTC, ubamrein commented on Tests/UBFoundationTests/Networking/ConcurrentNetworkTests.swift
> +        let url = URL(string: "https://s3-eu-central-1.amazonaws.com/app-test-static-fra.meteoswiss-app.ch/v1/warnings_with_outlook_with_naturalhazards_de.json")!
Hier sollten wir vielleicht andere Beispieldaten nehmen.

2023-01-26 07:24 UTC, ubamrein commented on Sources/UBFoundation/Networking/Concurrency/UBURLDataTask+Concurrency.swift
> +            switch resultTuple.result {
https://sonarcloud.io/project/issues?open=AYWslhTy-ICnse7PVrG5&id=UbiqueInnovation_ubkit-ios 

Ergibt hier glaub ich schon Sinn. Gibt ja nur zwei cases

2023-01-26 08:02 UTC, zimmermannubique commented on Sources/UBFoundation/Networking/UBURLRequestModifier.swift
> +                var newRequest = originalRequest
Ist deep, aber hat da noch kein payload, drum ok.

2023-01-26 08:03 UTC, zimmermannubique commented on Sources/UBFoundation/Networking/UBURLRequestModifier+TokenAuthorization.swift
> +public extension UBAsyncURLRequestTokenAuthorization {
können wir dann machen, wenn ubique mal was anderes macht ;-)

2023-01-26 08:31 UTC, ubamrein commented on Sources/UBFoundation/Networking/UBURLRequestModifier.swift
> +                var newRequest = originalRequest
Dann würde ich das so als Doc-Kommentar hinschreiben. Finde das ist nicht ersichtlich :)

2023-01-26 15:00 UTC, maerki commented on Sources/UBFoundation/Networking/UBURLRequestModifier.swift
> +                var newRequest = originalRequest
Deep copy sollte recht effizient sein, auch mit Payload

2023-01-30 10:46 UTC, ubamrein commented
> SonarCloud Quality Gate failed.    [![Quality Gate failed](https://camo.githubusercontent.com/4ea51c1f64ee3746f631653a02ab678ca6a3efb5f5cb474402faed2e3dcf90b5/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f6661696c65642d313670782e706e67)](https://sonarcloud.io/dashboard?id=UbiqueInnovation_ubkit-ios&pullRequest=23)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=CODE_SMELL) [4 Code Smells](https://sonarcloud.io/project/issues?id=UbiqueInnovation_ubkit-ios&pullRequest=23&resolved=false&types=CODE_SMELL)
> 
> [![No Coverage information](https://camo.githubusercontent.com/86785eaa572e061f5ecb3f8bf1cbb7b8eca44925083f92d067805b4362cead0c/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f4e6f436f766572616765496e666f2d313670782e706e67)](https://sonarcloud.io/component_measures?id=UbiqueInnovation_ubkit-ios&pullRequest=23) No Coverage information [![15.5%](https://camo.githubusercontent.com/efef8d7f6abcfdf5c67f93cc5bf65fa6c176ccbc2b89d16309748853e95b3863/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f32302d313670782e706e67)](https://sonarcloud.io/component_measures?id=UbiqueInnovation_ubkit-ios&pullRequest=23&metric=new_duplicated_lines_density&view=list) [15.5% Duplication](https://sonarcloud.io/component_measures?id=UbiqueInnovation_ubkit-ios&pullRequest=23&metric=new_duplicated_lines_density&view=list)

Die SonarCloud 'Code-Smells' könnte man noch resolven. Scheinen mir sinnvoll zu sein (bzgl Test, warum ist der auskommentiert?).

2023-02-02 10:42 UTC, maerki commented on Sources/UBFoundation/Networking/Concurrency/UBURLDataTask+Concurrency.swift
> +    func startCronStream<T>(decoder: UBURLDataTaskDecoder<T>) -> AsyncThrowingStream<(T, MetaData), Error> {
Weils bei uns früher so hiess, aber ja, verwirrt nur ohne Mehrwert. Auf `startStream` umbenennen.

2023-02-02 10:50 UTC, maerki commented
addFailureRecoveryStrategy fehlt noch, sonst noch API? würde schon vorschlagen, alles abzubilden, glaube ist mühsamer, das schritt für schritt hinzuzufügen

2023-02-02 10:56 UTC, maerki commented
Habe gerade noch überlegt, die API von TaskConfig so anzupassen, dass dies möglich ist:
`
UBURLDataTask
.with(requestModifier: AuthModifier())
.with(failureRecoveryStrategy: TokenRefreshRecoveryStrategy())
.loadOnce(url: url)
`

Könnte man erreichen, in dem die load-APIs grundsätzlich auf `TaskConfig` implementiert wären und verschieden "Modifier" immer eine neue Config zurückgeben. (Lohnt sich der Aufwand?)

`loadOnce` mit `URL` oder `URLRequest` wäre unabhängig noch cool.

2023-02-07 13:41 UTC, merged